from fastapi import APIRouter, Depends, HTTPException, Body
from sqlalchemy.orm import Session
from typing import Optional, Dict, Any
from datetime import datetime

from app.database import get_db
from app.models.intelligence import Alert, Observation
from app.models.actor import Actor

router = APIRouter(tags=["Alerts"])

@router.get("")
def get_alerts(
    db: Session = Depends(get_db),
    severity: Optional[str] = None,
    acknowledged: Optional[int] = None,
    limit: int = 50
):
    """
    Return all alerts generated by the crawler and AI attribution pipeline.
    """
    q = db.query(Alert)
    if severity:
        q = q.filter(Alert.severity == severity)
    if acknowledged is not None:
        q = q.filter(Alert.acknowledged == acknowledged)

    alerts = q.order_by(Alert.created_at.desc()).limit(limit).all()

    result = []
    for a in alerts:
        actor_name = "Global"
        if a.actor_id:
            act = db.query(Actor).filter(Actor.id == a.actor_id).first()
            if act:
                actor_name = act.actor_name

        result.append({
            "id": a.id,
            "alert_type": a.alert_type,
            "title": a.title,
            "description": a.description,
            "severity": a.severity,
            "actor_id": a.actor_id,
            "actor_name": actor_name,
            "observation_id": a.observation_id,
            "entity_type": a.entity_type,
            "entity_value": a.entity_value,
            "confidence": a.confidence,
            "created_at": a.created_at.isoformat() if a.created_at else None,
            "acknowledged": bool(a.acknowledged),
        })
    return result


@router.post("/{alert_id}/ack")
def acknowledge_alert(alert_id: int, db: Session = Depends(get_db)):
    """
    Mark an alert as acknowledged by the analyst.
    """
    alert = db.query(Alert).filter(Alert.id == alert_id).first()
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    alert.acknowledged = 1
    db.commit()
    return {"status": "acknowledged", "alert_id": alert_id}


@router.post("")
def create_alert(
    payload: Dict[str, Any] = Body(...),
    db: Session = Depends(get_db)
):
    """
    Create a new threat intelligence alert.
    """
    alert = Alert(
        alert_type=payload.get("alert_type", "ANOMALY_DETECTED"),
        title=payload.get("title", "Threat Anomaly"),
        description=payload.get("description", ""),
        severity=payload.get("severity", "MEDIUM"),
        actor_id=payload.get("actor_id"),
        observation_id=payload.get("observation_id"),
        entity_type=payload.get("entity_type"),
        entity_value=payload.get("entity_value"),
        confidence=payload.get("confidence", 0.8),
        created_at=datetime.utcnow(),
        acknowledged=0,
    )
    db.add(alert)
    db.commit()
    db.refresh(alert)
    return {"status": "created", "alert_id": alert.id}
